In [102]:
import pandas as pd
df = pd.read_csv('tuition_fee.csv')
import matplotlib.pyplot as plt
df = df.drop("學校統計處代碼", axis='columns')
df = df.rename(columns={"日間學制學士班學雜費收費基準-醫學系": "醫學系學士"})
df = df.rename(columns={"日間學制學士班學雜費收費基準-牙醫學系": "牙醫學系學士"})
df = df.rename(columns={"日間學制學士班學雜費收費基準-醫學院": "醫學院學士"})
df = df.rename(columns={"日間學制學士班學雜費收費基準-工學院": "工學院學士"})
df = df.rename(columns={"日間學制學士班學雜費收費基準-理農學院": "理農學院學士"})
df = df.rename(columns={"日間學制學士班學雜費收費基準-商學院": "商學院學士"})
df = df.rename(columns={"日間學制學士班學雜費收費基準-文法學院": "文法學院學士"})
df = df.rename(columns={"日間學制學士班學雜費收費基準-其他": "其他學士"})
df = df.rename(columns={"日間學制副學士學雜費收費基準(五專後2年、二專)-工業類": "工業類副學士"})
df = df.rename(columns={"日間學制副學士學雜費收費基準(五專後2年、二專)-商管類": "商管類副學士"})
df = df.rename(columns={"日間學制副學士學雜費收費基準(五專後2年、二專)-醫護類": "醫護類副學士"})
df = df.rename(columns={"日間學制副學士學雜費收費基準(五專後2年、二專)-其他": "其他副學士"})
df['其他副學士'][769]

'34,520~35,520'

In [86]:
df['醫學系學士']=df['醫學系學士'].str.replace(',', '')
df['牙醫學系學士']=df['牙醫學系學士'].str.replace(',', '')
df['醫學院學士']=df['醫學院學士'].str.replace(',', '')
df['工學院學士']=df['工學院學士'].str.replace(',', '')
df['理農學院學士']=df['理農學院學士'].str.replace(',', '')
df['商學院學士']=df['商學院學士'].str.replace(',', '')
df['文法學院學士']=df['文法學院學士'].str.replace(',', '')
df['其他學士']=df['其他學士'].str.replace(',', '')
df['工業類副學士']=df['工業類副學士'].str.replace(',', '')
df['商管類副學士']=df['商管類副學士'].str.replace(',', '')
df['醫護類副學士']=df['醫護類副學士'].str.replace(',', '')
df['其他副學士']=df['其他副學士'].str.replace(',', '')

In [91]:

df['醫學系學士']=pd.to_numeric(df['醫學系學士'], errors='coerce')
#df['修課人次合計'] = pd.to_numeric(Attendance_110['修課人次合計'].str.replace(',', ''))
#df[df['其他副學士'] > 0]
df['牙醫學系學士']=pd.to_numeric(df['牙醫學系學士'], errors='coerce')
df['醫學院學士']=pd.to_numeric(df['醫學院學士'], errors='coerce')
df['工學院學士']=pd.to_numeric(df['工學院學士'], errors='coerce')
df['理農學院學士']=pd.to_numeric(df['理農學院學士'], errors='coerce')
df['商學院學士']=pd.to_numeric(df['商學院學士'], errors='coerce')
df['文法學院學士']=pd.to_numeric(df['文法學院學士'], errors='coerce')
df['其他學士']=pd.to_numeric(df['其他學士'], errors='coerce')
df['工業類副學士']=pd.to_numeric(df['工業類副學士'], errors='coerce')
df['商管類副學士']=pd.to_numeric(df['商管類副學士'], errors='coerce')
df['醫護類副學士']=pd.to_numeric(df['醫護類副學士'], errors='coerce')
df['其他副學士']=pd.to_numeric(df['其他副學士'], errors='coerce')
df[df['其他副學士'] > 0]

,學年度,設立別,學校類別,學校名稱,醫學系學士,牙醫學系學士,醫學院學士,工學院學士,理農學院學士,商學院學士,文法學院學士,其他學士,工業類副學士,商管類副學士,醫護類副學士,其他副學士
31,106,公立,技專校院,國立高雄海洋科技大學,0,0,0,26277,26063,22812,0,26277,0.0,0.0,0.0,19847.0
47,106,公立,技專校院,國立臺南護理專科學校,0,0,0,0,0,0,0,0,0.0,0.0,18524.0,18524.0
79,106,私立,技專校院,輔英科技大學,0,0,56610,53870,0,53870,0,0,0.0,0.0,NaN,35195.0
85,106,私立,技專校院,正修學校財團法人正修科技大學,0,0,0,54735,0,0,47597,47597,41282.0,35684.0,0.0,37405.0
94,106,私立,技專校院,中國科技大學,0,0,0,51658,0,45025,0,51658,39162.0,33963.0,0.0,36082.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
757,110,私立,技專校院,經國管理暨健康學院,0,0,0,0,50423,0,0,53423,0.0,33705.0,37716.0,35294.0
758,110,私立,技專校院,大同技術學院,0,0,0,47116,47116,47116,0,0,0.0,0.0,0.0,35583.0
762,110,私立,技專校院,仁德醫護管理專科學校,0,0,0,0,0,0,0,0,0.0,32183.0,36023.0,34746.0
764,110,私立,技專校院,慈惠醫護管理專科學校,0,0,0,0,0,0,0,0,39798.0,34370.0,38599.0,36112.0
768,110,私立,技專校院,聖母醫護管理專科學校,0,0,0,0,0,0,0,0,0.0,37196.0,37196.0,37196.0